### ISSUE TITLE
Support question: Lua code available as a separate package?

### ISSUE THREAD

**Issue by pgundlach** [Josef-Friedrich/nodetree#1]
nodetree looks useful to me. Is the Lua code available as a separate package that gets a box as the input?

**Comment by Josef-Friedrich** [comment]
The Lua code is unfortunately very well “hidden”  in the dtx markup. In my texlive installation the Lua code of the package can be found at

```
/usr/local/texlive/texmf-dist/tex/luatex/nodetree/nodetree.lua
```

If you write a little bit of boilerplate code nodetree analyzes boxes out of the box:

```tex
\setbox0\hbox{\vbox{\hbox{abc}}\vbox{x}}
\directlua{
  nodetree = require("nodetree")
  nodetree.set_default_options()
  nodetree.analyze(tex.getbox(0))
}
\bye
```

![box.tex](https://cloud.githubusercontent.com/assets/545838/23082707/cc525652-f55a-11e6-8fd9-42fe568050bd.png)

**Comment by pgundlach** [comment]
Thank you, I'll have a look (the output is very nice!)
