### ISSUE TITLE
Proposal for the different verbosity levels of the field

### ISSUE THREAD

**Issue by Josef-Friedrich** [Josef-Friedrich/nodetree#37]
* `verbosity=0`:  `'L'`
* `verbosity=1`:  `76 ('L')`
* `verbosity=2`:  `char: 76 ('L')`
* `verbosity=3`:  `char: 76 (0x4c, 'L')`

**Comment by lemzwerg** [comment]
Good idea!  The only question is what to do if we have `'???'`...

**Comment by Josef-Friedrich** [comment]
* `verbosity=0`:  `'L'` or `76`
* `verbosity=1`:  `76 ('L')`
* `verbosity=2`:  `char: 76 ('L')`
* `verbosity=3`:  `char: 76 (0x4c, 'L')`

**Comment by lemzwerg** [comment]
I think that number 76 out of the blue is confusing.  What about

* `verbosity=0`: `'L'` or `char76`
* `verbosity=1`: `76 ('L')`
* `verbosity=2`: `char: 76 ('L')`
* `verbosity=3`: `char: 76 (0x4c, 'L')`

**Comment by lemzwerg** [comment]
I retract my suggestion.  [Your idea](https://github.com/Josef-Friedrich/nodetree/issues/37#issuecomment-1671361690) is the right one.

**Comment by lemzwerg** [comment]
Fixed with commit 534413328b23707a5f90b1396385d717810cfd69.

Please close this issue :slightly_smiling_face:
