### ISSUE TITLE
`8whatsit7latelua.tex` sends output to console

### ISSUE THREAD

**Issue by lemzwerg** [Josef-Friedrich/nodetree#40]
Contrary to other files in the `examples` directory, `8whatsit7latelua.tex` sends it output to the console.  This is not a problem per se but different, which makes it stand out during `make doc` behaviour.  I suggest that its output gets diverted to a log file as with its siblings.

**Comment by Josef-Friedrich** [comment]
That sounds reasonable.

**Comment by lemzwerg** [comment]
Fixed with commit 667ad84c7bc1e9b438aa04508c3d336520b48c73.
