### ISSUE TITLE
displaying `tail` for hyphenate and friends necessary?

### ISSUE THREAD

**Issue by lemzwerg** [Josef-Friedrich/nodetree#42]
Given that the current code of `nodetree` displays the whole node tree for `head` I wonder whether it makes sense at all to show `tail` – AFAICS, this information is always redundant, corresponding to the last line of the `head` tree.

My suggestion is to remove this, adding a remark to the documentation instead.

**Comment by Josef-Friedrich** [comment]
I agree with you

**Comment by lemzwerg** [comment]
Fixed with commit 7fc3867918e74e82095d8a2df03717eb88441556.
