### ISSUE TITLE
utf8 not in Lua 5.1

### ISSUE THREAD

**Issue by pgundlach** [Josef-Friedrich/nodetree#8]
`nodetree.lua` line 29:

    local utfchar           = utf8.char

Lua 5.1 does not have the `utf8` library (Lua 5.1 is the default version in LuajitTeX). So I get an error 

    attempt to index global 'utf8' (a nil value)

LuaJitTeX does include the slnunicode library. So a solution could be to write:

    utf8 = utf8 or unicode.utf8

beforehand.

(nodetree version 2.1)

**Comment by Josef-Friedrich** [comment]
Thank you for your bug report. Could you please review the commit, so that I can upload a new version to CTAN.

**Comment by pgundlach** [comment]
Works fine, thank you very much. (BTW: nodetree is very useful!)
