### ISSUE TITLE
Incorrect visualization

### ISSUE THREAD

**Issue by lemzwerg** [Josef-Friedrich/nodetree#9]
[nodetree 2.2]
[LuaTeX, Version 1.15.0 (TeX Live 2022), Development id: 7509]

Consider this input code file `foo.texi`, to be processed with `PDFTEX=luatex texi2pdf foo.texi`

```texinfo
\input nodetree.tex

\input texinfo

@set txicodequoteundirected
@set txicodequotebacktick

@NodetreeRegisterCallback{postline}

@t{`foo'} -- @code{`foo'}

@bye
```

and which produces the following output.

![image](https://user-images.githubusercontent.com/1630245/206657775-27c58043-f0b5-434e-8dd7-9744306d0e05.png)

On my (UTF-8) GNU/Linux console, I see the following, which doesn't look right partially.

![image](https://user-images.githubusercontent.com/1630245/206655800-5d64b203-fef9-47e2-a4f9-fc20b5046ab4.png)

**Comment by lemzwerg** [comment]
If I pipe the output into a file and view it with `less`, I get the following, which is better.

![image](https://user-images.githubusercontent.com/1630245/206667283-e814525e-c5c8-4b69-8781-be985724d230.png)

I think that using the term `char` within a `GLYPH` object is misleading.  In reality, it is just a glyph index, which accidentally might have the same value as the corresponding input character.  Not being yet acquainted with luatex internals I guess that `char` is the name of a field in the `GLYPH` structure.  In that case I suggest that you show  something like
```
GLYPH char: 102 (0x66, 'f')
```
to emphasize that this is *not* the input character code.  Of course, non-printable ASCII characters must be printed in an alternative form.

**Comment by Josef-Friedrich** [comment]
Thank you for your excellent bug report.

From the LuaTeX reference manual (Version 1.15) page 133

char - number - the character index in the font

**Comment by Josef-Friedrich** [comment]
related issue #6

**Comment by Josef-Friedrich** [comment]
I could reproduce this bug. I had to install `texinfo`: `sudo apt install texinfo`

**Comment by lemzwerg** [comment]
Thanks for the quick fix!

> char - number - the character index in the font

This is it exactly – everybody working with fonts (me included – I'm the maintainer of FreeType) except some parts of the TeX world doesn't call this a 'character index' but a 'glyph index'.  But I admit that I don't know LuaTeX well enough yet to really comment on that because it seems that this value probably serves more than a single purpose depending on the subtype of the 'glyph' node.  As far as I can see, it should be called 'character index' for subtype 'character' and 'glyph index' for all later stages (i.e., other subtypes)...
